### ISSUE TITLE
Mauvaise modale à la suppression d'un plugin

### ISSUE THREAD

**Issue by AndreLeclercq** [EvntBoard/application#3]
Lors de la suppression de plugin c'est la mauvaise modal qui s'ouvre.
<img width="241" alt="Capture d’écran 2021-01-05 à 11 01 18" src="https://user-images.githubusercontent.com/52776632/103632957-5b6add80-4f45-11eb-86d3-c09f5321c39f.png">

**Comment by evandikt** [comment]
La personne qui a developper cette modal, a omis de faire le fichier de messages et a donc utilisé ceux de Board :) Mais ca gère bien les plugins
