### ISSUE TITLE
Pas de titre sur le menu déroulant du formulaire des triggers

### ISSUE THREAD

**Issue by AndreLeclercq** [EvntBoard/application#5]
Il manque un titre pour rendre plus explicite le menu déroulant.
<img width="527" alt="Capture d’écran 2021-01-05 à 10 36 17" src="https://user-images.githubusercontent.com/52776632/103633508-1a26fd80-4f46-11eb-949c-6107d50af424.png">

**Comment by evandikt** [comment]
C'était une propriété mal passé sur le composant `Select` :)

👍
